Gemfile
Version used is consistent with other Rails applications.
=> LIBSEARCH-1. Added "pg" gem for Postgres

Gemfile
=> LIBSEARCH-1. Fixed typo in Gemfile

Gemfile.lock
Ran "bundle install" and updated Gemfile.lock file.
=> LIBSEARCH-1. Updated Gemfile.lock

Gemfile, app/views/quick_search/search/index.html.erb, config/quick_search_config.yml, config/searchers/lib_answers_config.yml, config/searchers/lib_guides_config.yml, env_example
- Updated files to incorporate LibAnswers Searcher
https://issues.umd.edu/browse/LIBSEARCH-6
=> LIBSEARCH-6. Create LibAnswers Searcher.

Gemfile, Gemfile.lock, app/views/quick_search/search/index.html.erb, config/locales/en.yml, config/quick_search_config.yml, config/searchers/world_cat_config.yml, env_example
https://issues.umd.edu/browse/LIBSEARCH-5
=> LIBSEARCH-5. Updated changes for the WorldCat searcher.

config/locales/en.yml
https://issues.umd.edu/browse/LIBSEARCH-12
=> LIBSEARCH-12. Label "LibGuides" as "Research Guides"

Gemfile, app/views/quick_search/search/index.html.erb, config/locales/en.yml, config/quick_search_config.yml, config/searchers/database_finder_config.yml, env_example
https://issues.umd.edu/browse/LIBSEARCH-10
=> LIBSEARCH-10. Added Database Finder searcher

Gemfile, Gemfile.lock, app/views/quick_search/search/index.html.erb, config/locales/en.yml, config/quick_search_config.yml, config/searchers/database_finder_config.yml, config/searchers/world_cat_knowledge_base_config.yml, env_example
https://issues.umd.edu/browse/LIBSEARCH-11
=> LIBSEARCH-11. Create WorldCat Knowledge Base Searcher.

app/assets/stylesheets/application.css.scss, app/controllers/application_controller.rb
The UMD style, colors, and server environment banners were added to the
quick_search-umd_theme. This adds the helper methods from the engine to
our controller and adds the theme engine's SCSS.
https://issues.umd.edu/browse/LIBSEARCH-24
https://issues.umd.edu/browse/LIBSEARCH-25
=> LIBSEARCH-25 Add UMD Libraries Theme

Gemfile, Gemfile.lock, app/views/quick_search/search/index.html.erb, config/quick_search_config.yml, config/searchers/library_website_config.yml, env_example
https://issues.umd.edu/browse/LIBSEARCH-21
=> LIBSEARCH-21. Added Library Website searcher

config/routes.rb
This adds the route to the searchumd app for the 'library web site'
searcher pages.
https://issues.umd.edu/browse/LIBSEARCH-22
=> LIBSEARCH-22 Add native search interface for website search

Dockerfile-solr, README.md, docker_config/solr/conf/schema.xml
schema.xml was taken from the stock Apache Nutch v1.14
https://issues.umd.edu/browse/LIBSEARCH-47
=> LIBSEARCH-47. Initial implementation of Solr Dockerfile

Dockerfile-nutch, README.md, docker_config/nutch/conf/nutch-site.xml, docker_config/nutch/conf/regex-urlfilter.txt, docker_config/nutch/urls/seed.txt
https://issues.umd.edu/browse/LIBSEARCH-44
=> LIBSEARCH-44. Initial implemenation of Apache Nutch Dockerfile

config/locales/en.yml
https://issues.umd.edu/projects/LIBSEARCH/issues/LIBSEARCH-50
=> LIBSEARCH-50. Changed "WorldCat" title to "WorldCat (Search)"

Gemfile, app/views/quick_search/search/index.html.erb, config/locales/en.yml, config/quick_search_config.yml, config/searchers/swiftype_config.yml, env_example
https://issues.umd.edu/browse/LIBSEARCH-62
=> LIBSEARCH-62. Added quick_search-swiftype_searcher searcher

app/assets/stylesheets/application.css.scss, app/controllers/swiftype_search_controller.rb, app/views/swiftype_search/index.html.erb, config/routes.rb, config/searchers/swiftype_config.yml
https://issues.umd.edu/browse/LIBSEARCH-61
=> LIBSEARCH-61. Initial implementation of a Swiftype "native" interface

app/views/quick_search/search/index.html.erb, config/locales/en.yml, config/quick_search_config.yml, config/searchers/world_cat_discovery_api_article_config.yml
Added the configuration necessary for the world_cat_discovery_api_article
searcher.
https://issues.umd.edu/browse/LIBSEARCH-71
=> LIBSEARCH-71. Added world_cat_discovery_api_article searcher

Jenkinsfile
For use with the "searchumd-multibranch-pipeline" job
in Jenkins.
https://issues.umd.edu/browse/LIBSEARCH-94
=> LIBSEARCH-94. Initial Jenkinsfile configuration

Gemfile.lock
https://issues.umd.edu/browse/LIBSEARCH-104
=> LIBSEARCH-104. Updated searchers to latest "develop" commits

Dockerfile, Gemfile, Gemfile.lock
In "Gemfile" added a "source" line pointing to the UMD Nexus so that the
UMD-customized gems can be found.
Modifed the "Dockerfile", providing a dummy "SECRET_KEY_BASE"
environment variable so that the "asset:compile" step would succeed.
https://issues.umd.edu/browse/LIBSEARCH-104
=> LIBSEARCH-105. Update Dockerfile and Gemfile so Docker container builds

config/locales/en.yml
https://issues.umd.edu/browse/LIBSEARCH-109
=> LIBSEARCH-109. Changed "Ask Us!" to "FAQs from Ask Us!"

Gemfile.lock
https://issues.umd.edu/browse/LIBSEARCH-131
=> LIBSEARCH-131. Updated to latest umd-lib/quick_search-umd_theme

config/searchers/ebsco_discovery_service_api_article_config.yml
https://issues.umd.edu/browse/LIBSEARCH-115
=> LIBSEARCH-115. Fix EBSCO Article "see all" results link

Gemfile.lock, README.md
Also added upgrade instructions to README.md
https://issues.umd.edu/browse/LIBSEARCH-141
=> LIBSEARCH-141. Updated searchumd to use latest searchers

Gemfile, Gemfile.lock, config/searchers/ebsco_discovery_service_api_article_config.yml, config/searchers/world_cat_discovery_api_article_config.yml, env_example
Updated Gemfile and configuration files.
https://issues.umd.edu/browse/LIBSEARCH-74
=> LIBSEARCH-74. Update Article Searchers to link using OpenURL

config/best_bets.yml
Just received a request to make this change.
=> Fixed course reserves description
