config/application.rb
In Quick Search, some of the JavaScript files, such as
quick_search/app/assets/javascripts/quick_search/event_tracking.js.erb
Rails URL helpers, i.e.
```
url = '<%= url_helper.log_event_path %>';
```
This works correctly in development, because the JavaScript assets
are compiled dynamically, and the relevant configuration is in place.
When running in production, however, the JavaScript assets are
precompiled. In order to get the correct relative url root, the
"config/application.rb" file needs to configure the
"default_url_options" for the routes.
Without this configuration, the JavaScript URLs will use "/" as the
root URL, which will fail when a suburi is used.
=> LIBSEARCH-1. Fixed JavaScript issue with Rails url_helpers

.gitignore, Gemfile, Gemfile.lock, README.md, test/integration/home_page_test.rb, test/test_helper.rb
Added testing tools typically used on Rails projects:
* minitest-reporters for prettier minitest output
* simplecov (and simplecov-rcov) for coverage reports
* rubocop-checkstyle_formatter used with Jenkins for generating Rubocop
report.
Added a simple integration test.
=> LIBSEARCH-1. Added additional test tools

Gemfile.lock
Updated "loofah" gem to v2.2.1 to take care of a GitHub security
vulnerability warning.
Updated "searcher" gems to bring in vulnerability fix updates for
those gems.
Ran the following command:
```
> bundle update loofah quick_search-lib_answers_searcher quick_search-lib_guides_searcher quick_search-world_cat_searcher
```
https://issues.umd.edu/browse/LIBSEARCH-13
=> LIBSEARCH-13. Updated searcher gems and "loofah" gem.

Gemfile, Gemfile.lock
Changed Gemfile to use the tagged 0.2.0 of quick_search-core. This is
that same GitHub commit as has being used before from the "develop"
branch, so it should not change the application.
https://issues.umd.edu/browse/LIBSEARCH-9
=> LIBSEARCH-9. Changed Gemfile to used "0.2.0" tag of quick_search-core

Gemfile.lock, config/locales/en.yml
Fixed issue in en.yml file which was preventing it from being processed.
Updated quick_search-lib_guides_searcher to latest development commit in Gemfile.lock
https://issues.umd.edu/browse/LIBSEARCH-23
=> LIBSEARCH-23. Fixed database names and updated lib_guides searcher in Gemfile.lock

config/searchers/database_finder_config.yml
The Database Finder REST API endpoint was changed as part of LIBWEB-4158
from
<SERVER_URL>/dbfinder/restapi/v1/search
to
<SERVER_URL>/dbfinder/list?queryScope=all&query=
This change simply updates the URL in the searchumd configuration.
https://issues.umd.edu/browse/LIBSEARCH-32
=> LIBSEARCH-32. Updated Database Finder REST API endpoint

config/locales/en.yml
Also added "website" relative link for when there are no
search results.
https://issues.umd.edu/browse/LIBSEARCH-37
=> LIBSEARCH-37. Changed "Library Website" label to "Website".

app/assets/stylesheets/application.css.scss
The quick_search engine handles asset imports for the theme. Adding it
to the manifest causes the compiled assets to swell to a very large size
https://issues.umd.edu/browse/LIBSEARCH-27
=> LIBSEARCH-27 Remove un-needed import from application.css

Dockerfile, docker_config/searchumd/rails_start.sh
Added a start script for the Rails application, including running the
rails server using "exec". This makes the Rails application run as
PID 1, so it receives the SIGTERM signal sent with "docker stop" is
run, allowing the application to gracefully shutdown.
https://issues.umd.edu/browse/LIBSEARCH-52
=> LIBSEARCH-52. Added start script for Rails application

Dockerfile-nutch, README.md, config/searchers/library_website_config.yml, docker_config/nutch/conf/nutch-site.xml, docker_config/nutch/conf/regex-urlfilter.txt, docker_config/nutch/urls/seed.txt, env_example
Modified the configuration to enable Solr server to be specified for
the library website searcher.
Added information to the README.md about setting up a Solr server for
use in the development environment.
https://issues.umd.edu/browse/LIBSEARCH-49
=> LIBSEARCH-49. Initial configuration to support Solr-based website search

Dockerfile-nutch, docker_config/nutch/conf/nutch-site.xml, docker_config/nutch/conf/solrindex-mapping.xml, docker_config/solr/conf/schema.xml
Modified the Dockerfile-nutch file to build Apache Nutch from the
UMD Apache Nutch repository, instead of the official Apache Nutch
repository.
This is needed so that the "umd-parsefilter-jsonld" plugin is included
in the Nutch implementation.
Also added "documentContent" field to Solr configuration, which is
populated by the "umd-parsefilter-jsonld" plugin.
https://issues.umd.edu/browse/LIBSEARCH-53
=> LIBSEARCH-53. Modified Dockerfile-nutch to use UMD Apache Nutch repo

Dockerfile-nutch, config/searchers/library_website_config.yml, docker_config/nutch/conf/nutch-site.xml, docker_config/nutch/conf/solrindex-mapping.xml, docker_config/solr/conf/schema.xml
Updated the query template for the quick_search-library_website_searcher
to use the "text" Solr field, instead of "content".
https://issues.umd.edu/browse/LIBSEARCH-54
=> LIBSEARCH-54. Updated search query to use "text" Solr field

README.md, app/controllers/website_search_controller.rb, app/views/website_search/_results.html.erb, app/views/website_search/index.html.erb, config/routes.rb, config/searchers/library_website_config.yml
Moved the controller and views for the website native interface out
of the quick_search-library_website_searcher into searchumd.
This simplifies the searcher, and avoids having to maintain separate
copies of the view templates.
Modified routes.rb, removed QuickSearchLibraryWebsiteSearcher engine,
because it was no longer needed, and added additional routes to satisfy
requirements in the view layouts (when used with the "native" interface)
to have access to certain routes.
https://issues.umd.edu/browse/LIBSEARCH-42
=> LIBSEARCH-42. Moved website "native" interface into searchumd

Gemfile.lock
Updated quick_search-world_cat_discovery_api_searcher so that
worldcat-discovery gem v1.2.0.1, and spira gem v3.1.0.1 would be
picked up.
This corrects the issue seen in LIBSEARCH-63
https://issues.umd.edu/browse/LIBSEARCH-63
=> LIBSEARCH-63. Updated quick_search-world_cat_discovery_api_searcher

Gemfile, Gemfile.lock, README.md, db/schema.rb
Updated searchumd to use the "umd-develop" branch of the UMD QuickSearch fork
at https://github.com/umd-lib/quick_search.
https://issues.umd.edu/browse/LIBSEARCH-16
=> LIBSEARCH-16. Updated searchumd to use UMD QuickSearch fork

config/locales/en.yml, config/searchers/database_finder_config.yml, config/searchers/lib_answers_config.yml, config/searchers/lib_guides_config.yml, config/searchers/library_website_config.yml, config/searchers/swiftype_config.yml, config/searchers/world_cat_config.yml, config/searchers/world_cat_discovery_api_config.yml, config/searchers/world_cat_knowledge_base_config.yml
Added "no_results_link" properties to each of the searcher configuration
YAML files in the config/searchers/ directory. This enables the
"no_results_link" property to be parameterized using environment
variables, if necessary.
In the en.yml file, replaced "no_results_link" entries with nothing
so that the properties in the searcher configuration YAML files will
be used.
https://issues.umd.edu/browse/LIBSEARCH-15
=> LIBSEARCH-15 Modified "no_results_link" configuration for searchers

config/locales/en.yml
Modified the Apache Nutch searcher display name to "Website Option 1"
Modified the Swiftype searcher display name to "Website Option 2"
https://issues.umd.edu/browse/LIBSEARCH-95
=> LIBSEARCH-95. Modified display names for Nutch and Swiftype searchers

config/initializers/session_store.rb
Removed session_store.rb file, as it is no longer needed for
Rails 5.2.2.1
https://issues.umd.edu/browse/LIBSEARCH-77
=> LIBSEARCH-77. Removed session_store.rb

Gemfile.lock
Updated the "searchumd" application to use the latest NCSU QuickSearch
version, via the "umd-develop" branch in the "umd-lib/quick_search"
repository.
This incorporates NSCU pull requests of UMD changes for:
* LIBSEARCH-121
* LIBSEARCH-127
* LIBSEARCH-128
https://issues.umd.edu/browse/LIBSEARCH-129
=> LIBSEARCH-129. Updated searchumd to use latest NSCU QuickSearch version

config/searchers/ebsco_discovery_service_api_article_config.yml, config/searchers/ebsco_discovery_service_api_config.yml
https://issues.umd.edu/browse/LIBSEARCH-134
=> LIBSEARCH-134. Use HTTPS urls for EBSCO host.

app/controllers/website_search_controller.rb, config/searchers/library_website_config.yml
Modified the library website native interface link to use "query"
instead of "q" for specifying the search term.
This makes the native interface link work with Hippo, where "query"
HTTP parameter is used for the search term.
Modified the website controller in searchumd to also expect the
"query" parameter, instead of "q".
https://issues.umd.edu/browse/LIBSEARCH-143
=> LIBSEARCH-143. Library website native interface link now uses "query"

config/searchers/world_cat_discovery_api_article_config.yml, config/searchers/world_cat_discovery_api_config.yml
Update the "no_results_link" for the world_cat_discovery_api and
world_cat_discovery_api_article searchers to point at a URL that does
not display a warning about an empty query term.
Both searchers still point at the same URL, because there does not
appear to be a way to set a URL that can be limited to articles, for
the "article" searcher.
https://issues.umd.edu/browse/LIBSEARCH-147
=> LIBSEARCH-147. Updated WorldCat config to point to better no results URL

Dockerfile-solr, docker_config/solr/conf/solrconfig.xml, docker_config/solr/conf/update-stripSuffix.js
Added "update-stripSuffix.js" strip a specified suffix from a specifid
field.
Added solrconfig.xml to run the "update-stripSuffix.js" script when a
document is updated, and configured to strip "| UMD Libraries" from
the "title" field.
Updated Dockerfile-solr to include the additional files in the Solr
configuration.
https://issues.umd.edu/browse/LIBSEARCH-149
=> LIBSEARCH-149. Added Solr script to strip "| UMD Libraries" from title

.gitignore, Gemfile, Gemfile.lock, README.md, app/views/quick_search/search/index.html.erb, config/locales/en.yml, config/quick_search_config.yml, config/searchers/archives_space_config.yml, config/searchers/drum_config.yml, config/searchers/ebsco_discovery_service_api_article_config.yml, config/searchers/ebsco_discovery_service_api_config.yml, config/searchers/fedora_config.yml, config/searchers/internet_archive_config.yml, config/searchers/maryland_map_config.yml, env_example
Moved the following searchers into searchumd:
From "searchumd-special":
* quick_search-archives_space_searcher
* quick_search-drum_searcher
* quick_search-internet_archive_searcher
* quick_search-fedora_searcher
* quick_search-maryland_map_searcher
from searchumd "eds-develop" branch:
* quick_search-ebsco_discovery_service_api_searcher
Added the searcher config files for the added searchers.
Modified the searcher page to show all the searchers.
Re-ordered searcher configuration in "env_example" so searchers would be
in alphabetical order.
Removed en.yml customizations, except where needed to display the
correct text. This was done so that on the searcher results page, it was
clearer which searcher was returning which results.
https://issues.umd.edu/browse/LIBSEARCH-150
=> LIBSEARCH-150. Moved searchers into searchumd

docker_config/nutch/conf/nutch-site.xml
Added UMD custom "umd-index-title" index filter to populate the
"title" field with the filename of a PDF file, if a title cannot
otherwise be found.
Also removed extraneous whitespace.
https://issues.umd.edu/browse/LIBSEARCH-148
=> LIBSEARCH-148. Added Nutch "umd-index-title" index filter

docker_config/nutch/conf/nutch-site.xml, docker_config/nutch/conf/regex-urlfilter.txt, docker_config/nutch/sitemaps/sitemaps.txt, docker_config/nutch/umd_crawl, docker_config/nutch/urls/seed.txt
Modified Nutch configuration to improve fetching and parsing:
* The entire document is parsed for links, instead of just the first 64k
* All links in the document are fetched, instead of just the first 100
* The individual patent pages in "Plant Patents" have been excluded.
* Nutch now retrieves the sitemap.xml from the production website for its seed URLs.
* Added "umd_crawl" script to Nutch configuration to make Nutch crawl more flexible (i.e. not limited to what is possible with the "bin/crawl" command in Nutch.
https://issues.umd.edu/browse/LIBSEARCH-168
=> LIBSEARCH-168. Improved Nutch fetching and parsing

config/searchers/lib_guides_config.yml, env_example
Replaced the hard-coded URL in "config/searchers/lib_guides_config.yml"
with a "LIB_GUIDES_URL" property in the .env file.
https://issues.umd.edu/browse/LIBSEARCH-182
=> LIBSEARCH-182. Replaced hard-coded URL in config with .env property

docker_config/nutch/umd_crawl
Added a "JVM_MAX_RAM_PERCENTAGE" variable to the Nutch script, which
defaults to 90.0, if not otherwise set. Modified the start script to
supply the "JVM_MAX_RAM_PERCENTAGE" variable to the -XX:MaxRAMPercentage
Java system property, so that the JVM will use more than 25% of the
available RAM in the container.
https://issues.umd.edu/browse/LIBSEARCH-193
=> LIBSEARCH-193. Added "JVM_MAX_RAM_PERCENTAGE" to Nutch script

.env.test, Gemfile, Gemfile.lock, app/views/quick_search/search/index.html.erb, config/quick_search_config.yml, config/searchers/lib_guides_database_config.yml, db/schema.rb, env_example, test/searchers/loaded_link_test.rb
Gemfile pulls in the "develop" branch of the quick_search-lib_guides_database_searcher gem from GitHub.
https://issues.umd.edu/browse/LIBSEARCH-200
=> LIBSEARCH-200. Added lib_guides_database_searcher integration.

config/initializers/modify_http_client_to_use_system_certs.rb
On October 1, 2021, a root CA certificate that the "http_client" relied
on for verifying SSL certificates expired. The "http_client" ships with
its own set of "trusted" root CA certificates which apparently haven't
been updated for a number of years.
The expired certificate was preventing a number of searchers from making
HTTP requests.
As at least a short-term fixed, followed the suggestion in
"http_client" issue 445 to "monkey-patch" the HTTPClient class to
use the CA certificates from the system.
https://issues.umd.edu/browse/LIBSEARCH-206
=> LIBSEARCH-206. SSL Root CA certification fix

Dockerfile
Replaced "/search" in "RAILS_RELATIVE_URL_ROOT" environment variable
with "/", because the "/search" subpath is no longer necessary.
The "/search" subpath was used when searchumd was its own front-end
application, in order allow a search home page to be provided. Since
searchumd is no longer a front-end application, but is used purely
as a backemd, the "/search" subpath is not needed.
Also removed the "SCRIPT_NAME" environment variable, because it does
not appear to be used, or necessary.
https://issues.umd.edu/browse/LIBSEARCH-205
=> LIBSEARCH-205. Fixed searchumd GUI when port forwarding
